version: "3.9"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: genasoft-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 3s
      retries: 10
