name: API Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./api/api/GenaSoft.Atos.sln

      - name: Build
        run: dotnet build ./api/api/GenaSoft.Atos.sln -c Release --no-restore

      - name: Publish API
        run: dotnet publish ./api/api/Atos.Api/Atos.Api.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: GENASOFT_API_APPNAME_PLACEHOLDER
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      # --- Opcional: instalar browsers do Playwright no App Service (placeholder) ---
      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}
      # - name: Playwright install on App Service (placeholder)
      #   run: |
      #     az webapp ssh --name GENASOFT_API_APPNAME_PLACEHOLDER --resource-group RG_PLACEHOLDER --command "playwright install --with-deps"

      # --- Opcional: EF migrations (placeholder) ---
      # - name: Run EF Migrations (placeholder)
      #   run: |
      #     echo "Execute migrations via az webapp ssh / container exec conforme App Service Linux v2"
