name: deploy-api

on:
  push:
    branches: [ "main", "chore/cleanup-estrutura" ]  # incluo sua branch p// testar antes do merge
  pull_request:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Debug: listar arquivos
        run: |
          pwd
          ls -la
          echo "---- localizar csproj ----"
          find . -maxdepth 2 -type f -name "*.csproj" | sed 's|^\./||'

      # se seu csproj está na raiz:
      - name: Publish API
        run: dotnet publish ./Atos.Api.csproj -c Release -o ./publish
      # (se estiver em Atos.Api/Atos.Api.csproj, troque o caminho acima)

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: enasoft-api-dev-mdo01
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
