name: deploy-api

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./Atos.sln

      # Se sua API está na raiz:
      - name: Publish API
        run: dotnet publish ./Atos.Api.csproj -c Release -o ./publish
      # (ou, se estiver em pasta Atos.Api/, troque para:)
      # run: dotnet publish ./Atos.Api/Atos.Api.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: enasoft-api-dev-mdo01
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
